version: '3.3'
services:
    php:
        build:
            context: ./config/php.local
            dockerfile: .Dockerfile
        container_name: php
        volumes:
            - './app:/var/www/html'
        depends_on:
            - mariadb

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - '80:80'
            - '443:443'
        links:
            - 'php'
        volumes:
            - './app:/var/www/html'
            - './config/nginx:/etc/nginx/conf.d'

    mariadb:
        image: mariadb:10.4
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./mysql:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
        links:
            - mariadb
        ports:
            - 8080:80

    selenium:
       image: selenium/standalone-chrome
       extra_hosts:
             - "simple-docker-php-main-selenium-1:172.18.0.6"
       links:
           - php
       ports:
           - 4444:4444